// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-BNv_nn08AbR65Ja_Mi2XajLqgAZZ_Tg',
    appId: '1:56252143042:web:2114cbf5fd3d330b8db25b',
    messagingSenderId: '56252143042',
    projectId: 'atividadefinalandre',
    authDomain: 'atividadefinalandre.firebaseapp.com',
    storageBucket: 'atividadefinalandre.firebasestorage.app',
    measurementId: 'G-PS6K8VMXTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1bbxc4DVO9wvZ9BEBQ4iOKoVp1wUz8QM',
    appId: '1:56252143042:android:2d7de014e0174ef78db25b',
    messagingSenderId: '56252143042',
    projectId: 'atividadefinalandre',
    storageBucket: 'atividadefinalandre.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-BNv_nn08AbR65Ja_Mi2XajLqgAZZ_Tg',
    appId: '1:56252143042:web:a5b8d2450953f1c98db25b',
    messagingSenderId: '56252143042',
    projectId: 'atividadefinalandre',
    authDomain: 'atividadefinalandre.firebaseapp.com',
    storageBucket: 'atividadefinalandre.firebasestorage.app',
    measurementId: 'G-DLMGMM00ZK',
  );
}
